version: "3.9"
services:
    user_service_psql:
        image: postgres:17-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=lifeat_user_service_psql
        restart: always
        volumes:
            - ./db/user_service:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        restart: always
        ports:
            - "6379:6379"

    zookeeper:
        image: docker.io/bitnami/zookeeper:3.9
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: "bitnami/kafka:latest"
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
